version: "3"
services:
  server:
    build:
      context: ./
    ports:
      - "3001:3001"
    container_name: backend-justoapp
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules
